behaviors:
  GesThor:
    trainer_type: ppo

    hyperparameters:
      batch_size: 512
      buffer_size: 5120
      learning_rate: 3e-4
      beta: 0.005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 5
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 1
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        encoding_size: 256
        learning_rate: 3e-4

    # Trainer configurations common to all trainers
    keep_checkpoints: 1
    checkpoint_interval: 300000
    max_steps: 1e6
    time_horizon: 128
    summary_freq: 1000
    threaded: true
    init_path: null

env_settings:
  env_path: ./gesthor_server_build.x86_64
  env_args: null
  base_port: 6006
  num_envs: 1
  seed: 0

engine_settings:
  width: 84 
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false

#checkpoint_settings:
  # run_id: gesthor_visual
  # initialize_from: null
  # load_model: false
  # resume: false
  # force: true
  # train_model: false
  # inference: false

# environment_parameters:
#   wrong_stop_penalty:
#     curriculum:
#       - name: wrong_stop_penalty_0.05 # The '-' is important as this is a list
#         completion_criteria:
#           measure: progress
#           behavior: Gesture
#           signal_smoothing: true
#           min_lesson_length: 10
#           threshold: 0.2
#         value: 0.05
#       - name: wrong_stop_penalty_0.1 # The '-' is important as this is a list
#         completion_criteria:
#           measure: progress
#           behavior: Gesture
#           signal_smoothing: true
#           min_lesson_length: 10
#           threshold: 0.4
#         value: 0.1
#       - name: wrong_stop_penalty_0.15 # The '-' is important as this is a list
#         completion_criteria:
#           measure: progress
#           behavior: Gesture
#           signal_smoothing: true
#           min_lesson_length: 10
#           threshold: 0.6
#         value: 0.15
#       - name: wrong_stop_penalty_0.20 # The '-' is important as this is a list
#         completion_criteria:
#           measure: progress
#           behavior: Gesture
#           signal_smoothing: true
#           min_lesson_length: 10
#           threshold: 0.8
#         value: 0.20
#       - name: wrong_stop_penalty_0.25
#         value: 0.25
